# version: 'latest'

services:

db:
  image: mysql:8.0.21
  container_name: db_students
  environment:
    MYSQL_DATABASE: db_students
    MYSQL_ROOT_PASSWORD: 1234
  
  ports: 
  - 3306:3306

  volumes:
    - ./db:/var/lib/mysql

  restart: always